name: Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        run: |
          cd gfwlist-python
          python -m pip install --upgrade pip
          pip install maturin

      - name: Build wheels
        run: |
          cd gfwlist-python
          maturin build --release

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: target/wheels/*

  publish:
    name: Publish wheels to PyPI
    runs-on: ubuntu-latest
    needs: build_wheels
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: wheels/

      - name: Move wheels
        run: |
          mkdir dist
          find wheels/ -type f -name "*.whl" -exec mv {} dist/ \;

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
